//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaApeN4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public string Cedula { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<decimal> Nota2 { get; set; }
        public Nullable<decimal> Supletorio { get; set; }
        public string Estado { get; set; }
    }
}
